apiVersion: v1
kind: Service
metadata:
  name: supermario-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: supermario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
